# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               alkaha
tagline:             
description:         koleksi terjemahan artikel teknologi front-end dan back-end ke dalam Bahasa Melayu.  Berkisar mengenai React, Ruby On Rails, Elixir, Phoenix dan lain-lain.
url:                 http://alkaha.github.io
baseurl:             ''
paginate:            3

# About/contact
author:
  name:              Alkaha Romli

# Custom vars
version:             1.0.0

gems:				 [jekyll-paginate]
